# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 03:11
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='default', editable=False, populate_from=models.CharField(max_length=30), unique_with=('<django.db.models.fields.related.ForeignKey>',)),
        ),
    ]
