# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 03:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='default', max_length=10),
        ),
    ]
