# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-27 03:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20170425_0338'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[(b'C', b'Caps'), (b'T', b'Tees')], max_length=20)),
            ],
        ),
    ]
